#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run full type check
npm run type-check

# Ensure build works
npm run build

# TODO: Add back test running after testing framework is set up
# npm run test 